apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.controller }}
    # traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend:
          serviceName: node
          servicePort: 80
